# Generated by Django 3.1.1 on 2020-09-06 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='read_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='read_by', to=settings.AUTH_USER_MODEL, verbose_name='read_by'),
        ),
        migrations.AddField(
            model_name='thread',
            name='first_online_state',
            field=models.BooleanField(default=False, verbose_name='chat_firts_online_status'),
        ),
        migrations.AddField(
            model_name='thread',
            name='second_online_state',
            field=models.BooleanField(default=False, verbose_name='chat_second_online_status'),
        ),
    ]
