# Generated by Django 3.1 on 2020-08-30 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_sheet', models.TextField(blank=True, choices=[('prettify', 'default'), ('desert', 'desert'), ('doxy', 'doxy'), ('sons-of-obsidian', 'sons-of-obsidian'), ('sunburst', 'sunburst')], default='desert', null=True)),
                ('mode_sheet', models.TextField(blank=True, choices=[('light', 'light'), ('dark', 'dark')], default='dark', null=True)),
                ('profile_pic', models.ImageField(blank=True, default='/default.png', null=True, upload_to='')),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, default='+254 7 06 522 473', max_length=20, null=True)),
                ('gender', models.TextField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Not set', max_length=10, null=True)),
                ('bio', models.CharField(blank=True, default='I love discuzz since it is the best discussion platform.', max_length=200, null=True)),
                ('programming_languages', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Java', 'Java'), ('Javascript', 'Javascript'), ('C', 'C'), ('C#', 'C#'), ('C++', 'C++'), ('Objective-c', 'Objective-C'), ('Php', 'Php'), ('Python', 'Python'), ('Javascript', 'Javascript'), ('Ruby', 'Ruby'), ('Perl', 'Perl'), ('Clojure', 'Clojure'), ('Scala', 'Scala'), ('Go', 'Go'), ('R*', 'R*'), ('Tcl', 'Tcl'), ('Lua', 'Lua'), ('Bash', 'Bash'), ('Visual Basic.NET', 'Visual Basic.NET'), ('Haskel', 'Haskel')], max_length=125, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.TextField(blank=True, default='offline', max_length=200, null=True)),
                ('friend_requests', models.ManyToManyField(related_name='friend_requests', to=settings.AUTH_USER_MODEL)),
                ('friends', models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        )
    ]
