# Generated by Django 3.1 on 2020-09-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200830_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='where',
        ),
        migrations.AddField(
            model_name='notification',
            name='question_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
