# Generated by Django 3.1 on 2020-09-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200901_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='topic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
