# Generated by Django 3.1 on 2020-09-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200901_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='where',
            field=models.TextField(blank=True, null=True),
        ),
    ]
