# Generated by Django 3.0.8 on 2020-07-21 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('paymentMode', models.CharField(blank=True, max_length=20, null=True)),
                ('paymentCode', models.CharField(max_length=20)),
                ('subtopic', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=1000)),
                ('discussionCode', models.CharField(default='100NO00DISCUSSION001yet11', max_length=100)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(blank=True, choices=[('visible', 'visible'), ('hidden', 'hidden')], default='visible', null=True)),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(blank=True, choices=[('java', 'Java'), ('javascript', 'Javascript')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_sheet', models.TextField(blank=True, choices=[('prettify', 'default'), ('desert', 'desert'), ('doxy', 'doxy'), ('sons-of-obsidian', 'sons-of-obsidian'), ('sunburst', 'sunburst')], default='desert', null=True)),
                ('mode_sheet', models.TextField(blank=True, choices=[('light', 'light'), ('dark', 'dark')], default='dark', null=True)),
                ('profile_pic', models.ImageField(blank=True, default='/default.png', null=True, upload_to='')),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, default='+254 7 06 522 473', max_length=20, null=True)),
                ('gender', models.TextField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Not set', max_length=10, null=True)),
                ('bio', models.CharField(blank=True, default='I love discuzz since it is the best discussion platform.', max_length=200, null=True)),
                ('programming_languages', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Java', 'Java'), ('Javascript', 'Javascript'), ('C', 'C'), ('C#', 'C#'), ('C++', 'C++'), ('Objective-c', 'Objective-C'), ('Php', 'Php'), ('Python', 'Python'), ('Javascript', 'Javascript'), ('Ruby', 'Ruby'), ('Perl', 'Perl'), ('Clojure', 'Clojure'), ('Scala', 'Scala'), ('Go', 'Go'), ('R*', 'R*'), ('Tcl', 'Tcl'), ('Lua', 'Lua'), ('Bash', 'Bash'), ('Visual Basic.NET', 'Visual Basic.NET'), ('Haskel', 'Haskel')], max_length=125, null=True)),
                ('notifications', jsonfield.fields.JSONField(default=[{'by': 'Discuzz', 'id': 0, 'type': 'visiting message'}])),
                ('hobbies', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.TextField(blank=True, default='offline', max_length=200, null=True)),
                ('friend_requests', models.ManyToManyField(related_name='friend_requests', to=settings.AUTH_USER_MODEL)),
                ('friends', models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('subtopic', models.CharField(max_length=50)),
                ('status', models.TextField(blank=True, choices=[('visible', 'visible'), ('hidden', 'hidden')], default='visible', null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.CharField(max_length=2000)),
                ('updateTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(blank=True, choices=[('unread', 'unread'), ('read', 'read')], default='unread')),
                ('state', models.TextField(blank=True, choices=[('reply', 'reply'), ('replied', 'replied')], default='reply')),
                ('email', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discuzz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(max_length=6000)),
                ('status', models.TextField(blank=True, choices=[('visible', 'visible'), ('hidden', 'hidden')], default='visible', null=True)),
                ('reply_time', models.DateTimeField(auto_now_add=True)),
                ('comments', models.ManyToManyField(blank=True, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('discussion_code', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.Create')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('commented_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(blank=True, choices=[('visible', 'visible'), ('hidden', 'hidden')], default='visible', null=True)),
                ('commented_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('commented_to', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.Discuzz')),
            ],
        ),
    ]
