# Generated by Django 3.0.2 on 2020-01-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_usersignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField()),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
    ]
