# Generated by Django 3.1 on 2020-08-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_userextension'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtension',
        ),
    ]
