# Generated by Django 3.0.2 on 2020-01-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_quizfive_quizfour_quizsix_quizthree_quiztwo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quizfour',
            new_name='Quizfourone',
        ),
    ]
