# Generated by Django 3.0.2 on 2020-01-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20200128_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionfour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField()),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
    ]
