# Generated by Django 3.0.2 on 2020-03-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_questionfour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add',
        ),
        migrations.DeleteModel(
            name='Questionfour',
        ),
        migrations.DeleteModel(
            name='Quizfive',
        ),
        migrations.DeleteModel(
            name='Quizfourone',
        ),
        migrations.DeleteModel(
            name='Quizone',
        ),
        migrations.DeleteModel(
            name='Quizsix',
        ),
        migrations.DeleteModel(
            name='Quizthree',
        ),
        migrations.DeleteModel(
            name='Quiztwo',
        ),
        migrations.DeleteModel(
            name='search',
        ),
        migrations.DeleteModel(
            name='UserSignup',
        ),
    ]
