# Generated by Django 3.0.2 on 2020-04-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('admin', models.CharField(max_length=20)),
                ('paymentMode', models.CharField(max_length=20)),
                ('paymentCode', models.CharField(max_length=20)),
                ('subtopic', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
