# Generated by Django 3.0.2 on 2020-04-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_auto_20200401_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discuzz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_code', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=2000)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
