# Generated by Django 3.0.2 on 2020-04-02 16:20

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_discuzz'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='discussion_code',
            field=models.CharField(default='100NO00DISCUSSION001yet11', max_length=100),
        ),
        migrations.AddField(
            model_name='discuzz',
            name='reply_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 4, 2, 16, 20, 6, 812574, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discuzz',
            name='discussion_code',
            field=models.CharField(default='100NO00DISCUSSION001yet11', max_length=100),
        ),
    ]
