# Generated by Django 3.0.2 on 2020-04-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_auto_20200402_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create',
            old_name='create_time',
            new_name='createTime',
        ),
        migrations.RenameField(
            model_name='create',
            old_name='discussion_code',
            new_name='discussionCode',
        ),
    ]
