# Generated by Django 3.0.2 on 2020-04-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_auto_20200402_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('update', models.CharField(max_length=2000)),
                ('updateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
