# Generated by Django 3.0.2 on 2020-05-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_auto_20200427_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuzz',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
