# Generated by Django 3.0.2 on 2020-05-11 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0017_discuzz_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discuzz',
            name='likes',
        ),
        migrations.AddField(
            model_name='discuzz',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
