# Generated by Django 3.0.2 on 2020-05-11 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0018_auto_20200511_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuzz',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
