# Generated by Django 3.0.2 on 2020-05-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_discuzz_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discuzz',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='discuzz',
            name='likes',
        ),
    ]
