# Generated by Django 3.0.2 on 2020-05-11 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0021_auto_20200511_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuzz',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
