# Generated by Django 3.0.2 on 2020-05-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuzz',
            name='reply',
            field=models.TextField(max_length=6000),
        ),
    ]
