# Generated by Django 3.0.2 on 2020-05-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0026_auto_20200525_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
